-- Active: 1740894750177@@127.0.0.1@1433@v5_81_sp2@dbo
TRUNCATE TABLE formmain_0019;

TRUNCATE TABLE formson_0020;

TRUNCATE TABLE formmain_0023;

TRUNCATE TABLE formson_0024;

TRUNCATE TABLE CTP_AFFAIR;

TRUNCATE TABLE COL_SUMMARY;

TRUNCATE TABLE CTP_USER_HISTORY_MESSAGE;
TRUNCATE TABLE WF_WORKITEM_RUN;

SELECT * FROM formmain_0019;

SELECT * FROM formson_0020;

SELECT * FROM formmain_0023;

SELECT * FROM formson_0024;

SELECT * FROM CTP_AFFAIR;

SELECT * FROM COL_SUMMARY;

SELECT * FROM CTP_TEMPLATE;

SELECT * FROM  WF_WORKITEM_RUN; 

select * from cap_form_auth_info;

SELECT * FROM ORG_MEMBER
