spring:
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: "root"
    password: "123123"
    url: "jdbc:mysql://localhost:3306/blockchain"

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

blockchain:
  url: "http://localhost:8545/"
  gas-limit: "0x2fefd8"
  admin:
  coin-address:
  item-address:
  shop-address:
